%--------------------------------------------------------------------
% PURPOSE:
%
% This routine generates a structure containing strings for the scalar-valued 
% Lagrange shape functions for P^k discontinuous finite elements in 1D 
% with degree k = 0,1,2,3.
%
% Unlike for the 2D DG basis, here the basis functions are defined on the
% reference element [0,1].
%
%--------------------------------------------------------------------

function [basis]= basis_lagrange1D(fem)

fprintf('Compute the shape functions elements: %s\n', fem);

switch fem
    case 'P0'
        nln = 1;
        c = 1;
        basis = struct('num',nln,...
            'coeff',c,...
            'fbasis',{'c(1,1)'},...
            'Gbasis',{'0'});
        
    case 'P1'
        nln = 2;
        [c]= matrix_coeff1D_P1(nln);
        basis=struct('num',nln,...
            'coeff',c,...
            'fbasis',{'c(1,1).*csi + c(2,1)',...
                      'c(1,2).*csi + c(2,2)'},...
            'Gbasis',{'c(1,1).*1 + 0',...
                        'c(1,2).*1 + 0'});

    case 'P2'
        nln = 3;
        [c] = matrix_coeff1D_P2(nln);
        basis = struct('num',nln,...
            'coeff',c,...
            'fbasis',{'c(1,1).*csi.^2 + c(2,1).*csi + c(3,1)',...
                      'c(1,2).*csi.^2 + c(2,2).*csi + c(3,2)',...
                      'c(1,3).*csi.^2 + c(2,3).*csi + c(3,3)'},...
            'Gbasis',{'c(1,1).*2.*csi + c(2,1).*1 + 0',...
                      'c(1,2).*2.*csi + c(2,2).*1 + 0',...
                      'c(1,3).*2.*csi + c(2,3).*1 + 0'});
                  
    case 'P3'
        nln = 4;
        [c] = matrix_coeff1D_P3(nln);
        basis = struct('num', nln,...
            'coeff',c,...
            'fbasis',{'c(1,1).*csi.^3 + c(2,1).*csi.^2 + c(3,1).*csi + c(4,1)',...
                      'c(1,2).*csi.^3 + c(2,2).*csi.^2 + c(3,2).*csi + c(4,2)',...
                      'c(1,3).*csi.^3 + c(2,3).*csi.^2 + c(3,3).*csi + c(4,3)',...
                      'c(1,4).*csi.^3 + c(2,4).*csi.^2 + c(3,4).*csi + c(4,4)'},...
            'Gbasis',{'c(1,1)*3.*csi.^2 + c(2,1)*2.*csi + c(3,1).*1 + 0',...
                      'c(1,2)*3.*csi.^2 + c(2,2)*2.*csi + c(3,2).*1 + 0',...
                      'c(1,3)*3.*csi.^2 + c(2,3)*2.*csi + c(3,3).*1 + 0',...
                      'c(1,4)*3.*csi.^2 + c(2,4)*2.*csi + c(3,4).*1 + 0'});
end

end
