%--------------------------------------------------------------------
% PURPOSE:
%
% This routine evaluates the scalar shape functions and their derivatives
% at the quadrature nodes 1D on the reference element [0,1], i.e.,
%
% dphiq  -> scalar shape functions (volume integrals): matrix nqn x nln
% Grad   -> derivative of the scalar shape functions: matrix nqn x nln
%
% INPUT : nodes -> array with the quadrature nodes on the reference interval
%               [0,1]
%         shape_basis -> struct generated by basis_lagrange1D()
%--------------------------------------------------------------------

function [dphiq, Grad] = evalshape1D(shape_basis, nodes, nln)

% fprintf('Evaluate the shape functions 1D on the reference element\n');

nqn = length(nodes);
dphiq = zeros(nqn, nln);
Grad = zeros(nqn, nln);

c = shape_basis(1).coeff; % needed by eval()

for s=1:nln % loop over the number of scalar shape functions

    csi = nodes;
    dphiq(:,s) = eval(shape_basis(s).fbasis);
    Grad(:,s) = eval(shape_basis(s).Gbasis);
    
    
end
end